name: Build and Push Docker Image

on:
  push:
    branches:
      - main  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-app .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/flask-app




  #       🧠 What this does (in simple terms):
	# •	Runs the workflow when you push code to main
	# •	Checks out your code
	# •	Logs into Docker Hub (you’ll set the credentials as secrets soon)
	# •	Builds the Docker image
	# •	Pushes the image to Docker Hub
