name: Terraform Destroy

on: 
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2
    
    - name: Set Up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.0

    - name: terraform init
      id: Init
      run: terraform init
      working-directory: terraform

    - name: terraform destroy
      id: destroy
      run: terraform destroy
      working-directory: terraform